---
- name: Add nginx signing key
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    state: present

- name: Add nginx repository
  apt_repository: repo={{item}} state=present update_cache=yes
  with_items:
    - 'deb http://nginx.org/packages/ubuntu/ xenial nginx'
    - 'deb-src http://nginx.org/packages/ubuntu/ xenial nginx'

- name: install nginx
  package:
    name: nginx
    state: present

- name: apply nginx config template to /etc/nginx/conf.d/mattermost.conf
  template:  
    src: mattermost.conf.j2
    dest: /etc/nginx/conf.d/mattermost.conf

- name: remove nginx default site
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: restart nginx
