---
- name: Create cron job to automatically update SSL cert (systemd)
  cron:
    name: "Renew letsencrypt SSL certs"
    minute: "47"
    hour: "23"
    month: "*"
    day: "15"
    job: "systemctl stop nginx && /opt/letsencrypt/letsencrypt-auto renew --quiet --no-self-upgrade && systemctl start nginx"
