---
- name: Create cron job to automatically update SSL cert (systemd)
  cron:
    name: "Renew letsencrypt SSL certs"
    minute: "15"
    hour: "0"
    month: "*"
    weekday: "6"
    job: "systemctl stop nginx && certbot renew --quiet && systemctl start nginx"
