---
- name: Install git
  package:
    name: git
    state: present

- name: git clone letsencrypt/letsencrypt
  git:
    repo: https://github.com/letsencrypt/letsencrypt
    dest: /opt/letsencrypt/

- name: Create letsencrypt config file /opt/letsencrypt/cli.ini
  template:
    src: cli.ini.j2
    dest: /opt/letsencrypt/cli.ini

- name: Get SSL certificate from letsencrypt
  command: /opt/letsencrypt/letsencrypt-auto certonly -c /opt/letsencrypt/cli.ini --agree-tos
  args:
    creates: /etc/letsencrypt/live/{{ ansible_fqdn }}/fullchain.pem
