---
- name: Install software-properties-common
  package:
    name: software-properties-common
    state: present

- name: Add certbot repository
  apt_repository:
    repo: 'ppa:certbot/certbot'

- name: Install certbot
  package:
    name: certbot
    state: present

- name: Create letsencrypt config file /etc/letsencrypt/cli.ini
  template:
    src: cli.ini.j2
    dest: /etc/letsencrypt/cli.ini

- name: Get SSL certificate from letsencrypt
  command: certbot certonly --non-interactive --agree-tos
  args:
    creates: /etc/letsencrypt/live/{{ ansible_fqdn }}/fullchain.pem
